home/urls.py
from django.urls import path

import home.views as home

app_name = 'home'

urlpatterns = [
    path('', home.home_view, name='index'),
    path('submit/', home.submit_run, name='submit'),
    path('runs/<str:username>/', home.runner_view, name='runner'),
    path('runs/<str:username>/<int:run_pk>/', home.run_view, name='run'),
    path('results/<str:username>/', home.user_results, name='user'),
    path('results/<str:username>/<str:runner>', home.user_results, name='user_runner'),
]

oauth/urls.py
from django.urls import path

import oauth.views as oauth

app_name = 'oauth'

urlpatterns = [
    path('', oauth.do_oauth, name='login'),
    path('logout/', oauth.log_out, name='logout'),
    path('callback/', oauth.callback, name='callback'),
]

speedrun_web/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('oauth/', include('oauth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('debug/', include(debug_toolbar.urls))] + urlpatterns

home/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class RunManager(models.Manager):
    def get_runs(self, user, runner=None):
        if runner:
            return self.filter(user=user, run__user=runner).order_by('-pk')
        else:
            return self.filter(user=user).order_by('-pk')


class Run(models.Model):
    user = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=255)
    duration = models.IntegerField()
    closest_offset = models.IntegerField()
    no_guesses = models.IntegerField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = RunManager()

    def __str__(self):
        return '{}: {}'.format(self.user.username, self.title)

    def get_winners(self):
        return Result.objects.filter(run=self.pk, offset=0)

    def get_closest(self):
        return Result.objects.filter(run=self.pk, offset=self.closest_offset)

    def get_url(self):
        uri = reverse('home:run', kwargs={'username': self.user.username, 'run_pk': self.pk})
        return '{}{}'.format(settings.SITE_URL, uri)


class ResultManager(models.Manager):
    def get_wins(self, user, runner=None):
        if runner:
            runner_user = User.objects.get(username=runner)
            return self.filter(offset=0, user=user, run__user=runner_user)
        else:
            return self.filter(offset=0, user=user)


class Result(models.Model):
    user = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    guess = models.IntegerField()
    offset = models.IntegerField()
    run = models.ForeignKey(Run, models.CASCADE, blank=True, null=True)
    objects = ResultManager()

    def __str__(self):
        offset = '+{}'.format(self.offset) if self.offset > 0 else self.offset
        return '{}: {} ({})'.format(self.user, self.user, offset)

home/views.py
import json
import logging
from pprint import pformat
from django.conf import settings
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from home.models import Run, Result

logger = logging.getLogger('app')
config = settings.CONFIG


def home_view(request):
    #  View: /
    runs = Run.objects.all()
    runners = []
    for run in runs:
        if run.user not in runners:
            runners.append(run.user)
    data = {'runners': runners}
    return render(request, 'home.html', {'data': data})


def runner_view(request, username):
    #  View: /<str:username>/
    try:
        logger.debug('username: {}'.format(username))
        user = User.objects.get(username=username)
        runs = Run.objects.get_runs(user)
        data = {'runs': runs, 'user': user}
        return render(request, 'runner.html', {'data': data})
    except Exception as error:
        logger.exception(error)
        return redirect('home:index')


def run_view(request, username, run_pk):
    #  View: /<str:username>/<int:run_pk>/
    try:
        logger.debug('username: {}'.format(username))
        logger.debug('run_pk: {}'.format(run_pk))
        user = User.objects.get(username=username)
        run = Run.objects.get(pk=run_pk)
        results = Result.objects.filter(run=run)
        data = {'run': run, 'results': results, 'user': user}
        return render(request, 'run.html', {'data': data})
    except Exception as error:
        logger.exception(error)
        return redirect('home:index')


def user_results(request, username, runner=None):
    #  View: /results/<str:username>/
    try:
        logger.debug('username: {}'.format(username))
        user = User.objects.get(username=username)
        if runner:
            runner_user = User.objects.get(username=runner)
            results = Result.objects.filter(user=user, run__user=runner_user).order_by('-pk')
        else:
            results = Result.objects.filter(user=user).order_by('-pk')
        data = {'results': results, 'user': user, 'runner': runner}
        return render(request, 'user.html', {'data': data})
    except Exception as error:
        logger.exception(error)
        return redirect('home:index')


@csrf_exempt
@require_http_methods(['POST'])
def submit_run(request):
    #  View: /submit/
    try:
        data = json.loads(request.body.decode())
        logger.debug(pformat(data))
        user, created = User.objects.get_or_create(username=data['user'])
        run = Run(
            user=user,
            title=data['title'],
            duration=data['duration'],
            closest_offset=data['closest_offset'],
            no_guesses=data['no_guesses'],
        )
        run.save()

        for guess in data['data']:
            user, created = User.objects.get_or_create(username=guess['user'])
            result = Result(
                user=user,
                guess=guess['guess'],
                offset=guess['offset'],
                run=run,
            )
            result.save()

        data = {'url': run.get_url()}
        return JsonResponse(data)

    except Exception as error:
        logger.exception(error)
        data = {'error': error}
        return JsonResponse(data, status=400)

templates/home.html
{% extends "main.html" %}
{% block home_active %}active{% endblock %}
{% block title %}Home{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row mt-2">
        <div class="col">
            <h1>Speedrun Fun</h1>
            <p class="lead">Runners with submitted runs.</p>

            {% for runner in data.runners %}
                <h4>
                    {{ runner.username|get_runs_by_username|length }} -
                    <a href="{% url 'home:runner' runner.username %}">{{ runner.username }}</a>
                </h4>
            {% endfor %}

        </div>
    </div>
{% endblock %}

templates/main.html
{% load staticfiles %}
{% load home_tags %}

<!doctype html>
<html lang="en">
<head>
	<!-- Required tags for bootstrap -->
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Meta -->
	<meta name="author" content="Shane Rice"/>
	<meta name="title" content="Speedrun Fun"/>
	<meta name="description" content="Speedrun Results and Estimates"/>

	<meta property="og:author" content="Shane Rice">
	<meta property="og:title" content="Speedrun Fun">
	<meta property="og:description" content="Speedrun Results and Estimates">
	<meta property="og:type" content="website">
	<meta property="og:url" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url 'home:index' %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% static 'images/logo.png' %}">
	<meta property="og:image:type" content="image/png">

	<title>Speedrun Fun - {% block title %}{% endblock %}</title>

	<!-- Media -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

	<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'font-awesome/css/all.min.css' %}" rel="stylesheet">
	<link href="{% static 'main/css/main.css' %}" rel="stylesheet">

	{% block head %}{% endblock %}
</head>
<body>

<!-- Main content -->
<div class="container-fluid">
    {% block heading %}
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mt-2">
            <a class="navbar-brand" href="{% url 'home:index' %}">{{ site_title_short }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
                    aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% block home_active %}{% endblock %}">
                        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                    </li>
                </ul>

                {% if not request.user.is_authenticated %}
                    <a href="{% url 'oauth:login' %}?next={{ request.path }}" class="btn btn-outline-info" role="button">
                        Log in with Twitch
                        <i class="fas fa-sign-in-alt"></i></a>
                {% else %}
                    <a href="https://www.twitch.tv/settings/profile" target="_blank" class="text-info mr-3">
                        {% if request.user.first_name %}{{ request.user.first_name }}{% else %}{{ request.user.username }}{% endif %}</a>
                    {% if user.is_staff %}
                        <a href="{% url 'admin:index' %}" class="btn btn-outline-primary mr-1" role="button">
                            Admin
                            <i class="fas fa-rocket"></i></a>
                    {% endif %}
                    <a href="" class="log-out btn btn-outline-info" role="button">
                        Log Out
                        <i class="fas fa-sign-out-alt"></i></a>
                {% endif %}
            </div>
        </nav>
    {% endblock %}

    {% block body %}{% endblock %}

    {% block footer %}{% endblock %}
</div>

{% if request.user.is_authenticated %}
    <form id="log-out" action="{% url 'oauth:logout' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.get_full_path }}">
    </form>
{% endif %}

<!-- JS imported at end to improve page loads -->
<script type="text/javascript" src="{% static 'bootstrap/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'font-awesome/js/all.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

{% block tail %}{% endblock %}

</body>
</html>

templates/run.html
{% extends "main.html" %}
{% block user_active %}active{% endblock %}
{% block title %}Run {{ data.run.title}} by {{ data.user.username }}{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>{{ data.run.title }}</h1>

            <table class="table">
                <tbody>
                <tr>
                    <th scope="row">Runner</th>
                    <td><a href="{% url 'home:runner' data.user.username %}">{{ data.user.username }}</a></td>
                </tr>
                <tr>
                    <th scope="row">Run Date</th>
                    <td>{{ data.run.created_at }}</td>
                </tr>
                <tr>
                    <th scope="row">Run Duration</th>
                    <td>{{ data.run.duration|fmt_seconds }}</td>
                </tr>
                <tr>
                    <th scope="row">Winners</th>
                    <td>
                    {% if data.run.get_winners %}
                        {{ data.run.get_winners|length }} -
                            {% for winner in data.run.get_winners %}
                                <a href="{% url 'home:user' winner.user.username %}">{{ winner.user.username }}</a> {% if not forloop.last %}, {% endif %}
                            {% endfor %}

                    {% else %}
                        No Winners
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Total Guesses</th>
                    <td>{{ data.run.no_guesses }}</td>
                </tr>
                </tbody>
            </table>

            <h4>User Guesses</h4>

            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">User</th>
                    <th scope="col">Guess</th>
                    <th scope="col">Offset</th>
                </tr>
                </thead>
                <tbody>
                {% for guess in data.results %}
                    <tr>
                        <td><a href="{% url 'home:user_runner' guess.user data.user.username %}">
                            {{ guess.user }}</a></td>
                        <td>{{ guess.guess|fmt_seconds }}</td>
                        <td>{{ guess.offset|fmt_offset }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}

templates/runner.html
{% extends "main.html" %}
{% block user_active %}active{% endblock %}
{% block title %}Runs from {{ data.user.username }}{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Runs from {{ data.user.username }}</h1>

            <h3>Runs</h3>

            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Total Guesses</th>
                    <th scope="col">Winners</th>
                    <th scope="col">Date</th>
                </tr>
                </thead>
                <tbody>

                {% for run in data.runs %}
                <tr>
                    <th scope="row">{{ run.pk }}</th>
                    <td><a href="{% url 'home:run' data.user.username run.pk %}">{{  run.title }}</a></td>
                    <td>{{  run.duration|fmt_seconds }}</td>
                    <td>{{  run.no_guesses }}</td>
                    <td>{{  run.get_winners|length }}</td>
                    <td>{{  run.created_at }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}

templates/user.html
{% extends "main.html" %}
{% block user_active %}active{% endblock %}
{% block title %}Guesses by {{ data.user.username }}{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Guesses</h1>

            <h3>by {{ data.user.username }}</h3>

        {% if data.runner %}
            <a href="{% url 'home:user' data.user.username %}" role="button" class="btn btn-sm btn-outline-primary my-1">
                Filtered by <strong>{{ data.runner }}</strong>. Click here to remove the filter.</a>
        {% endif %}

            {% get_result_wins data.user data.runner as wins %}
            <p class="lead">Total Wins: {{ wins|length }}</p>

            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Runner</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Guess</th>
                    <th scope="col">Offset</th>
                    <th scope="col">Date</th>
                </tr>
                </thead>
                <tbody>

                {% for result in data.results %}
                <tr>
                    <th scope="row">{{ result.run.pk }}</th>
                    <td><a href="{% url 'home:run' data.user.username result.run.pk %}">
                        {{ result.run.title }}</a></td>
                    <td><a href="{% url 'home:runner' result.run.user.username %}">
                        {{ result.run.user.username }}</a></td>
                    <td>{{ result.run.duration|fmt_seconds }}</td>
                    <td>{{ result.guess|fmt_seconds }}</td>
                    <td>{{ result.offset|fmt_offset }}</td>
                    <td>{{ result.run.created_at }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}